INSERT INTO achievement (name, points, description, link) VALUES
('Allow Cookies?', 2, 'Obtido ao entregar os Exploding Cookies para Avar Tar, Simon The Beggar, Ariella, Lorbas, King Markwin, Hjaern, Wyda, Hairycles e Orc King durante a missão 10 da What a Foolish Quest', 'https://www.tibiawiki.com.br/wiki/Allow_Cookies%3F_(Achievement)'),
('Allowance Collector', 2, 'Obtido ao quebrar 50 Piggy Banks', 'https://www.tibiawiki.com.br/wiki/Allowance_Collector_(Achievement)'),
('Alumni', 6, 'Pode ser obtido fazendo os dois addons masculinos do Mage Outfits ou os dois addons femininos do Summoner Outfits', 'https://www.tibiawiki.com.br/wiki/Alumni_(Achievement)'),
('Amateur Actor', 2, 'Obtido após finalizar a missão 4 da The Thieves Guild Quest', NULL),
('Annihilator', 5, 'Obtido após finalizar a Annihilator Quest', NULL),
('Arachnoise', 1, 'Obtido após falar para Grizzly Adams que você derrotou o boss The Bloodweb', NULL),
('Archpostman', 3, 'Obtido após finalizar a The Postman Missions Quest', NULL),
('Aristocrat', 4, 'Pode ser obtido fazendo os dois addons do Noble(wo)man Outfits', NULL),
('Ashes to Dust', 4, 'Obtido usando 500 vezes (com sucesso) a sua Blessed Wooden Stake em Demons e/ou Vampires', NULL),
('Askarak Nemesis', 1, 'Obtido após matar 100 Askarak Prince', NULL),
('Back from the Dead', 2, 'Obtido após falar para Grizzly Adams que você derrotou o boss Zanakeph', NULL),
('Back into the Abyss', 1, 'Obtido após falar para Grizzly Adams que você derrotou o boss Thul', NULL),
('Backpack Tourist', 1, 'Obtido após entregar a Old and Used Backpack para Sam, parte da Sam''s Old Backpack Quest', NULL),
('Bad Timing', 2, 'Obtido após emperrar um dos canivetes da Secret Service Quest 10 vezes', NULL),
('Bane of the Hive', 2, 'Pode ser obtido fazendo os dois addons do Insectoid Outfits', NULL),
('Beach Tamer', 2, 'Obtido completando a The Mermaid Marina Quest', NULL),
('Beak Doctor', 4, 'Pode ser obtido fazendo os dois addons do Afflicted Outfits', NULL),
('Bearbaiting', 1, 'Obtido ao domar um Bear', NULL),
('Bearhugger', 1, 'Obtido após completar a segunda missão da Barbarian Test Quest', NULL);

INSERT INTO achievement (name, points, description, link) VALUES
('Beautiful Agony', 2, 'Obtido após falar para Grizzly Adams que você derrotou o boss Ethershreck', NULL),
('Becoming a Bigfoot', 1, 'Obtido após virar um recruta na Bigfoot''s Burden Quest', NULL),
('Beneath the Sea', 3, 'Obtido ao domar uma Manta Ray', NULL),
('Berserker', 3, 'Obtido bebendo 100 Berserk Potions (Apenas knights podem fazer este achievement)', NULL),
('Beyonder', 3, 'Obtido após derrotar o The Pale Worm (Feaster of Souls Quest) e reportar seu feito ao npc Norbert', NULL),
('Bibliomaniac', 3, 'Obtido após adquirir a montaria Flying Book (utilizando o item Library Ticket em um Flying Book)', NULL),
('Blacknailed', 1, 'Obtido ao domar um Gravedigger utilizando um Nail Case (obtido após completar a The Gravedigger of Drefia Quest)', NULL),
('Blessed!', 2, 'Obtido terminando a The Blessed Stake Quest', NULL),
('Blood-Red Snapper', 1, 'Obtido após falar para Grizzly Adams que você derrotou o boss The Snapper', NULL),
('Bluebarian', 2, 'Obtido usando 500 Blueberry Bushes', NULL),
('Bone Brother', 1, 'Obtido ao entrar na Brotherhood of Bones na Dreamer''s Challenge Quest (Ao fazê-lo você não poderá adquirir o achievement Nightmare Knight)', NULL),
('Breaking the Ice', 1, 'Obtido após falar para Grizzly Adams que você derrotou o boss Shardhead', NULL),
('Brutal Politeness', 6, 'Pode ser obtido fazendo os dois addons do Barbarian Outfits', NULL),
('Bunny Slipped', 2, 'Obtido após entregar 7 Fake Rabbit''s Foot para o Rottin Wood na task Lucky Loop durante a Rottin Wood and the Married Men Quest', NULL),
('Buried the Baron', 1, 'Obtido após derrotar o boss The Baron from Below no final da Warzone 4', NULL),
('Call Me Sparky', 1, 'Obtido após fazer a task "Raiders of the Lost Spark" da Bigfoot''s Burden Quest', NULL),
('Champion of Chazorai', 4, 'Obtido após finalizar a missão 9 da The New Frontier Quest', NULL),
('Champion of Summer', 2, 'Obtido após matar 20 bosses lutando pela corte de verão após conversar com o NPC Shirtalis Of The Summer Court', NULL),
('Champion of Winter', 2, 'Obtido após matar 20 bosses lutando pela corte de inverno após conversar com o NPC Farhilorn Of The Winter Court', NULL),
('Chequered Teddy', 1, 'Obtido ao domar um Panda utilizando com o item Bamboo Leaves', NULL),
('Chitin Bane', 4, 'Obtido após fazer a tarefa "Dissolve Chitin" 100 vezes na War Against The Hive Quest', NULL),
('Choking on Her Venom', 1, 'Obtido após falar para Grizzly Adams que você derrotou o boss The Old Widow', NULL),
('Chorister', 1, 'Obtido após aprender todos os quatro Music Sheets', NULL),
('Clay Fighter', 3, 'Obtido após fazer um Pretty Clay Statue do Clay Lump', NULL),
('Clay to Fame', 6, 'Obtido após fazer cinco Pretty Clay Statue através de Clay Lumps', NULL),
('Cobbled and Patched', 6, 'Obtido após completar os dois addons do Makeshift Warrior Outfits', NULL),
('Cold As Ice', 6, 'Obtido após fazer dez Ice Mammoth de um Ice Cube', NULL),
('Confusion', 3, 'Obtido após fazer a tarefa "Destroy The Hive Crystals" 50 vezes na War Against The Hive Quest', NULL),
('Contender', 3, 'Ao desbloquear totalmente 10 criaturas do nível médio você ganha o achievement', NULL),
('Cookie Monster', 1, 'Pode ser obtido fazendo Cookies 20 vezes', NULL),
('Crawling Death', 1, 'Obtido após falar para Grizzly Adams que você derrotou o boss Fleshcrawler', NULL),
('Crystal Clear', 3, 'Pode ser obtido fazendo os dois addons do Crystal Warlord Outfits', NULL),
('Crystal Keeper', 1, 'Obtido após fazer a task "Crystal Keeper" da Bigfoot''s Burden Quest', NULL),
('Crystals in Love', 1, 'Obtido após fazer a task "Matchmaker" da Bigfoot''s Burden Quest', NULL),
('Cursed!', 3, 'Obtido sendo amaldiçoado por uma Claw of ''The Noxious Spawn''', NULL),
('Dark Voodoo Priest', 2, 'Obtido usando um Voodoo Doll em um jogador até acertá-lo', NULL),
('Dazzler', 3, 'Obtido após fazer a tarefa "Antenna Blinding" 50 vezes na War Against The Hive Quest', NULL),
('Death from Below', 2, 'Obtido após abrir o Abyssador Treasure Chest na Bigfoot''s Burden Quest', NULL),
('Death in the Depths', 2, 'Obtido após derrotar os bosses das Warzones 4, 5 e 6', NULL),
('Death on Strike', 4, 'Obtido ao abrir o báu de recompensas referente ao Deathstrike 50 vezes', NULL),
('Death Song', 3, 'Obtido após matar 300 Deepling Spellsingers', NULL),
('Deep Sea Diver', 4, 'Pode ser obtido andando aproximadamente 1.250.000 sqms em baixo da água (Em torno de 75 horas para ser completado)', NULL),
('Deer Hunt', 1, 'Obtido após matar 400 White Deer', NULL),
('Demonbane', 6, 'Pode ser obtido fazendo os dois addons do Demon Hunter Outfits', NULL),
('Demonic Barkeeper', 3, 'Pode ser obtido usando 250 Concentrated Demonic Blood', NULL),
('Depth Dwellers', 3, 'Obtido após matar 300 Deepling Warriors', NULL),
('Diplomatic Immunity', 4, 'Obtido ao abrir o báu de recompensas referente ao Abyssador 50 vezes', NULL);

INSERT INTO achievement (name, points, description, link) VALUES
('Do Not Disturb', 1, 'Obtido fechando janelas 100 vezes', NULL),
('Doctor! Doctor!', 2, 'Pode ser obtido após entregar 100 Medicine Pouches para Ottokar durante a Swamp Fever World Change (Sempre ativa no Taleon)', NULL),
('Dragon Mimicry', 2, 'Obtido ao domar um Dragonling', NULL),
('Dread Lord', 8, 'Obtido após receber o rank de Dread Lord pela Brotherhood of Bones na Dreamer''s Challenge Quest (Se você escolheu seguir os Nightmare Knights você não poderá fazer esse achievement)', NULL),
('Dream Catcher', 3, 'Obtido após reportar para Vanys ou Undal que você matou o boss The Nightmare Beast', NULL),
('Dream Warden', 5, 'Pode ser obtido fazendo os dois addons do Dream Warden Outfits', NULL),
('Dream Warrior', 6, 'Obtido após conseguir os dois addons do Dream Warrior Outfits', NULL),
('Dream Wright', 1, 'Obtido ao liberar um total de 100 Shimmying Butterflies', NULL),
('Dream''s Over', 1, 'Obtido após falar para Grizzly Adams que você derrotou o boss Tormentor', NULL),
('Duked It Out', 1, 'Obtido após derrotar o boss The Duke of the Depths no final da Warzone 6', NULL),
('Dungeon Cleaner', 3, 'Obtido após completar as 3 primeiras Warzones', NULL),
('Easter''s Knight', 5, '[Exclusivo Taleon] Obtido ao participar da luta contra o boss Ostara, no evento de Páscoa, realizado em abril', NULL),
('Efreet Ally', 3, 'Obtido após finalizar a The Djinn War pelo lado dos Green Djinns (Ao fazê-lo você não poderá adquirir o achievement Marid Ally)', NULL),
('Elite Hunter', 5, 'Obtido após receber o Rank de Elite Hunter na Paw and Fur', NULL),
('Ender of the End', 5, 'Obtido após derrotar o boss World Devourer na Heart of Destruction Quest', NULL),
('Ending the Horror', 2, 'Obtido ao completar pela primeira vez a missão A Retched Beggining.', NULL),
('Enter zze Draken!', 2, 'Obtido após falar para Grizzly Adams que você derrotou o boss Paiz the Pauperizer', NULL),
('Errand Boy', 1, '[Exclusivo Taleon] Obtido após terminar a Arito''s Task Quest', NULL),
('Exemplary Citizen', 4, 'Pode ser obtido fazendo os dois addons do Citizen Outfits', NULL),
('Exquisite Taste', 2, 'Obtido pescando 250 peixes através do método de Ice Fishing', NULL),
('Exterminator', 4, 'Obtido após fazer a tarefa "Kollos'' Killing" 100 vezes na War Against The Hive Quest', NULL),
('Fairy Teasing', 1, 'Obtido após dar use em 100 Dancing Fairy em Feyrist', NULL),
('Fall of the Fallen', 4, 'Obtido ao abrir o báu de recompensas referente ao Gnomevil 50 vezes', NULL),
('Fata Morgana', 2, 'Obtido ao domar um Dromedary', NULL),
('Ferumbras Power Nexus Nemesis', 5, '[Exclusivo Taleon] Obtido ao derrotar um Ferumbras Power Nexus na invasão do Ferumbras Revenge', NULL),
('Ferumbras''s Executioner', 5, '[Exclusivo Taleon] Obtido ao derrotar o Ferumbras na invasão do Ferumbras Revenge', NULL),
('Final Strike', 2, 'Obtido após abrir o Deathstrike Treasure Chest na Bigfoot''s Burden Quest', NULL),
('Firefighter', 2, 'Pode ser obtido após extinguir 500 fogos durante a Thornfire', NULL),
('Fireworks in the Sky', 2, 'Obtido após usar 250 Fireworks Rockets no chão (não conta se você usar na sua backpack)', NULL),
('Follower of Azerus', 4, 'Obtido completando a missão 9 da In Service of Yalahar Quest se você seguir todas as instruções do NPC Yalahari (Ao fazer este achievement, você não poderá adquirir o Follower of Palimuth nem o Turncoat)', NULL),
('Follower of Palimuth', 4, 'Obtido completando a missão 9 da In Service of Yalahar Quest se você seguir todas as instruções do NPC Palimuth (Ao fazer este achievement, você não poderá adquirir o Follower of Azerus nem o Turncoat)', NULL);

INSERT INTO achievement (name, points, description, link) VALUES
('Fool at Heart', 3, 'Pode ser obtido fazendo os dois addons do Jester Outfits', NULL),
('Forbidden Fruit', 1, 'Obtido ao comer a Forbidden Fruit', NULL),
('Fountain of Life', 1, 'Obtido bebendo da "fonte da vida" na entrada da Pits of Inferno', NULL),
('Free Items!', 3, 'Pode ser obtido após conseguir 50 itens em um Crate', NULL),
('Fried Shrimp', 2, 'Obtido ao domar uma Crustacea Gigantica', NULL),
('Friend of Elves', 1, 'Obtido ao domar um Enraged White Deer', NULL),
('Friend of the Apes', 4, 'Obtido após finalizar a The Ape City Quest', NULL),
('Funghitastic', 3, 'Pode ser obtido fazendo os dois addons do Soil Guardian Outfits', NULL),
('Gatherer', 2, 'Obtido após fazer a tarefa "Dissolved Chitin" 10 vezes na War Against The Hive Quest', NULL),
('Gear Up', 3, 'Obtido ao domar um Walker', NULL),
('Gem Cutter', 1, 'Obtido ao pegar o primeiro The Heart of the Sea na Liquid Black Quest', NULL),
('Gnome Friend', 2, 'Obtido após alcançar o rank 2 da Bigfoot''s Burden Quest', NULL),
('Gnome Little Helper', 1, 'Obtido após alcançar o rank 1 da Bigfoot''s Burden Quest', NULL),
('Gnomebane''s Bane', 2, 'Obtido após abrir o Gnomevil Treasure Chest na Bigfoot''s Burden Quest', NULL),
('Gnomelike', 3, 'Obtido após alcançar o rank 3 da Bigfoot''s Burden Quest', NULL),
('Gnomish Art Of War', 3, 'Obtido após entregar um Deathstrike''s Snippet, um Gnomevil''s Hat e um Abyssador''s Lash para Gnomission', NULL),
('Go With da Lava Flow', 1, 'Obtido ao completar a missão Into the Fire durante a Hero of Rathleton Quest', NULL),
('Godslayer', 4, 'Pode ser obtido ao acabar a Wrath of the Emperor Quest', NULL),
('Gold Digger', 4, 'Pode ser obtido cavando 100 Scarab Coins no deserto de Ankrahmun', NULL),
('Golden Sands', 3, 'Obtido ao domar um Sandstone Scorpion', NULL);

INSERT INTO achievement (name, points, description, link) VALUES
('Golem in the Gears', 4, 'Obtido após completar a Shadows of Yalahar Quest', NULL),
('Goo Goo Dancer', 1, 'Obtido ao limpar 100 Mucus Plugs', NULL),
('Gravedigger', 3, 'Obtido após finalizar a The Gravedigger of Drefia Quest.', NULL),
('Greenhorn', 2, 'Obtido após finalizar a Barbarian Arena Quest na dificuldade Greenhorn', NULL),
('Grinding Again', 1, 'Obtido após fazer a task "Yet Another Grinding" da Bigfoot''s Burden Quest', NULL),
('Guard Killer', 2, 'Obtido após fazer a tarefa "Kollos'' Killing" 10 vezes na War Against The Hive Quest', NULL),
('Guardian Downfall', 4, 'Obtido após matar 300 Deepling Guards', NULL),
('Happy Farmer', 1, 'Obtido cortando 200 wheat com um Scythe ou Squeezing Gear of Girlpower', NULL),
('Hat Hunter', 5, 'Obtido após completar a Ferumbras'' Ascension Quest', NULL),
('Headache', 2, 'Obtido após fazer a tarefa "Destroy The Hive Crystals" 10 vezes na War Against The Hive Quest', NULL),
('Heartburn', 3, 'Obtido após fazer a tarefa "Disrupt The Hives Digestion" 50 vezes na War Against The Hive Quest', NULL),
('Herbicide', 8, 'Obtido após completar a The Demon Oak Quest', NULL),
('Here, Fishy Fishy!', 1, 'Obtido após pescar 1.000 peixes', NULL),
('Hickup', 2, 'Obtido após fazer a tarefa "Disrupt The Hives Digestion" 10 vezes na War Against The Hive Quest', NULL),
('Hidden Powers', 2, 'Obtido ao usar um small ruby em um Helmet of the Ancients', NULL),
('High Inquisitor', 5, 'Obtido após finalizar a The Inquisition Quest', NULL),
('High-Flyer', 4, 'Obtido após viajar pelos tapetes voadores 1.000 vezes', NULL),
('Hippofoddermus', 1, 'Obtido ao alimentar por 100 vezes um hipopótamo de Issavi com Reed Balls', NULL),
('His Days are Counted', 1, 'Obtido após derrotar o boss Count of the Core no final da Warzone 5', NULL),
('Hissing Downfall', 2, 'Obtido após falar para Grizzly Adams que você derrotou o boss The Noxious Spawn', NULL),
('Hive Blinder', 4, 'Obtido após fazer a tarefa "Antenna Blinding" 100 vezes na War Against The Hive Quest', NULL),
('Hive Fighter', 1, 'Obtido após adquirir 300 War Exp na War Against The Hive Quest', NULL),
('Hive Infiltrator', 3, 'Obtido após fazer a tarefa "Kollos'' Killing" 50 vezes na War Against The Hive Quest', NULL),
('Hive War Veteran', 1, 'Obtido após adquirir 500 War Exp na War Against The Hive Quest', NULL),
('Homebrewed', 1, 'Obtido usando 50 Bunch of Sugar Cane em uma Distilling Machine', NULL);

INSERT INTO achievement (name, points, description, link) VALUES
('Honorary Barbarian', 1, 'Obtido após finalizar o Barbarian Test Quest', NULL),
('Honorary Gnome', 4, 'Obtido após alcançar o rank 4 da Bigfoot''s Burden Quest', NULL),
('Howly Silence', 1, 'Obtido após falar para Grizzly Adams que você derrotou o boss Hemming', NULL),
('Hunting Permit', 1, 'Ao desbloquear totalmente alguma criatura você ganha o achievement', NULL),
('Hunting with Style', 6, 'Pode ser obtido fazendo os dois addons do Hunter Outfits', NULL),
('Huntsman', 2, 'Obtido após ganhar o Rank de Huntsman na Paw and Fur', NULL),
('I Did My Part', 2, 'Obtido após dar use na estátua de Fafnar no início do evento The Lightbearer', NULL),
('I like it Fancy', 1, 'Obtido usando uma Small Enchanted Emerald em uma Dracoyle Statue', NULL),
('I need a Hug', 2, 'Pode ser obtido usando um Panda Teddy, um Stuffed Dragon, uma Baby Seal Doll e um Santa Doll, uma vez cada um', NULL),
('Ice Sculptor', 3, 'Pode ser obtido fazendo uma escultura de um Ice Mammoth com um Ice Cubes usando uma Obsidian Knife nele', NULL),
('Icy Glare', 1, 'Obtido ao domar um Ursagrodon', NULL),
('In Shining Armor', 6, 'Pode ser obtido fazendo os dois addons do Knight Outfits', NULL),
('Inquisition''s Arm', 2, 'Obtido após fazer os dois addons do Hand of the Inquisition Outfits', NULL),
('Inquisition''s Hand', 3, 'Obtido após derrotar King Zelos e reportar sua task para Jack Springer', NULL),
('Interior Decorator', 4, 'Obtido ao abrir 1000x um furniture kit (necessário apenas um, qualquer um)', NULL),
('Invader of the Deep', 2, 'Obtido ao matar 300 Deepling Scouts', NULL),
('Jamjam', 5, 'Obtido após entregar 100 peixes (Rainbow Trout e Green Perch, somando 100 no total) para o NPC Sinatuki', NULL),
('Jinx', 2, 'Obtido após usar 500 Lottery Tickets não premiados (os bons não contam)', NULL),
('Joke''s On You', 1, 'Obtido após abrir um present (explosive). Obtido durante o evento de páscoa, na NPC Hoaxette, perto do templo de Thais', NULL),
('Just Cracked Me Up!', 2, 'Obtido após falar para Grizzly Adams que você derrotou o boss Stonecracker', NULL),
('Kapow!', 1, 'Obtido após falar para Grizzly Adams que você derrotou o boss Bruise Payne', NULL),
('Keeper of the Flame', 2, 'Obtido após acender um dos Lightbearer Basins no evento The Lightbearer (apenas após o servidor completar com sucesso)', NULL),
('King of The Ring', 2, 'Obtido após falar para Grizzly Adams que você derrotou o boss Bretzecutioner', NULL),
('Knock on Wood', 3, 'Obtido ao domar um Tin Lizzard', NULL),
('Lacewing Catcher', 3, 'Obtido após domar uma Lacewing Moth usando uma Turquoise Tendril Lantern', NULL);

INSERT INTO achievement (name, points, description, link) VALUES
('Let the Sunshine In', 1, 'Obtido abrindo janelas de casas 100 vezes', NULL),
('Life on the Streets', 4, 'Pode ser obtido fazendo os dois addons do Beggar Outfits', NULL),
('Light-Fingered', 3, '[Exclusivo Taleon] Obtido após pegar uma jewel case durante a Nomad''s Land Quest', NULL),
('Lion King', 1, 'Obtido ao domar um Noble Lion', NULL),
('Lion''s Den Explorer', 1, 'Obtido ao completar a Lion''s Rock Quest', NULL),
('Little Adventure', 1, 'Ao desbloquear totalmente 10 criaturas do nível fácil você ganha o achievement', NULL),
('Little Ball of Wool', 1, 'Obtido ao domar uma Black Sheep', NULL),
('Little Big Adventure', 2, 'Ao desbloquear totalmente 100 criaturas do nível fácil você ganha o achievement', NULL),
('Lord of The Elements', 5, 'Obtido após finalizar a The Elemental Spheres Quest', NULL),
('Lord Protector', 8, 'Obtido após receber o rank de Lord Protector pela Nightmare Knights na Dreamer''s Challenge Quest (Se você escolheu seguir a Brotherhood of Bones você não poderá fazer esse achievement)', NULL),
('Lovely Dots', 3, 'Obtido ao domar uma Ladybug', NULL),
('Loyal Lad', 1, 'Obtido ao domar um Donkey', NULL),
('Lucid Dreamer', 2, 'Obtido após finalizar a quarta missão da Dreamer''s Challenge Quest', NULL),
('Lucky Devil', 4, 'Obter um Leviathan''s Amulet ao usar uma Fishing Rod no corpo de um Water Elemental ou Massive Water Elemental E obter uma Golden Armor de uma Slightly Rusted Armor', NULL),
('Lucky Horseshoe', 1, 'Obtido ao domar um Wild Horse', NULL),
('Luminous Kitty', 3, 'Obtido após adquirir a montaria Blazebringer, recompensa ao completar o evento The Lightbearer', NULL),
('Luring Silence', 2, 'Obtido ao completar pela primeira vez a missão Lure Silencers', NULL),
('Mageslayer', 1, 'Obtido após matar o Energized Raging Mage duas vezes', NULL),
('Magnetized', 2, 'Obtido ao domar um Ironblight', NULL),
('Mainstreet Nightmare', 2, 'Obtido após fazer os dois addons do Poltergeist Outfits', NULL),
('Make a Wish', 1, 'Obtido apagando 5 velas de Party Cakes', NULL),
('Manic', 4, 'Obtido após fazer a tarefa "Destroy The Hive Crystals" 100 vezes na War Against The Hive Quest', NULL),
('Marble Madness', 6, 'Pode ser obtido fazendo 5 Beautiful Marble Statues através de Pieces of Marble Rock', NULL),
('Marblelous', 3, 'Obtido após fazer uma Beautiful Marble Statue de uma Piece of Marble Rock', NULL),
('Marid Ally', 3, 'Obtido após finalizar a The Djinn War pelo lado dos Blue Djinns (Ao fazê-lo você não poderá adquirir o achievement Efreet Ally)', NULL);

INSERT INTO achievement (name, points, description, link) VALUES
('Masquerader', 3, 'Obtido usando 100 Costume Bags do NPC Stan', NULL),
('Master Hunter', 6, 'Ao desbloquear totalmente 100 criaturas do nível difícil você ganha o achievement', NULL),
('Master of The Nexus', 6, 'Obtido após pegar as recompensas da The Inquisition Quest', NULL),
('Master of War', 6, 'Pode ser obtido fazendo os dois addons do Warmaster Outfits', NULL),
('Master Thief', 4, 'Obtido após finalizar a The Thieves Guild Quest', NULL),
('Mastermind', 3, 'Obtido bebendo 100 Mastermind Potions (Apenas Sorcerers e Druids podem fazer este Achievement)', NULL),
('Matchmaker', 1, 'Obtido após completar a missão 3 da The Scatterbrained Sorcerer Quest ou completando a Eleonore Quest (Acesso a Laguna Islands)', NULL),
('Meat Skewer', 1, 'Obtido após falar para Grizzly Adams que você derrotou o boss The Bloodtusk', NULL),
('Merry Adventures', 2, 'Pode ser obtido completando a Rottin Wood and the Married Men Quest', NULL),
('Millennial Falcon', 3, 'Obtido após derrotar o Grand Master Oberon', NULL),
('Mind the Dog!', 2, 'Obtido ao domar um Modified Gnarlhound', NULL),
('Ministrel', 2, 'Obtido após usar os Instrumentos Musicais na ordem correta para acessar a sala de Vashresamun', NULL),
('Minor Disturbance', 2, 'Obtido após fazer a tarefa "Antenna Blinding" 10 vezes na War Against The Hive Quest', NULL),
('Mister Sandman', 2, 'Obtido dormindo 500 vezes em uma cama ou em um Cot (logout)', NULL),
('Modest Guest', 1, 'Obtido dormindo em uma Straw Mat 100 vezes (logout)', NULL),
('Moth Whisperer', 3, 'Obtido após domar uma Hibernal Moth usando uma Purple Tendril Lantern', NULL),
('Mutated Presents', 1, 'Obtido usando uma Obsidian Knife no corpo da The Mutated Pumpkin', NULL),
('Mystic Fabric Magic', 4, 'Obtido após completar os dois addons do Elementalist Outfits', NULL),
('Natural Born Cowboy', 1, 'Pode ser obtido ganhando sua primeira montaria', NULL),
('Natural Sweetener', 1, 'Pode ser obtido cortando 50x Sugar Canes', NULL),
('Navigational Error', 5, 'Obtido após falar com o NPC Navigator pela primeira vez', NULL),
('Nightmare Knight', 1, 'Obtido entrando na Nightmare Knights na Dreamer''s Challenge Quest (Ao fazê-lo você não poderá adquirir o achievement Bone Brother)', NULL),
('Nightmare Walker', 6, 'Pode ser obtido fazendo os dois addons do Nightmare Outfits (Se você escolheu seguir a Brotherhood of Bones você não poderá fazer esse achievement)', NULL),
('No More Hiding', 1, 'Obtido após falar para Grizzly Adams que você derrotou o boss Hide', NULL),
('Noblesse Obliterated', 6, 'Obtido após matar o boss Prince Drazzak', NULL),
('Nomad Soul', 2, 'Obtido após virar cidadão das seguintes cidades: Ab''Dendriel, Ankrahmun, Carlin, Darashia, Edron, Farmine, Kazordoon, Liberty Bay, Port Hope, Svargrond, Thais, Venore e Yalahar', NULL);

INSERT INTO achievement (name, points, description, link) VALUES
('Nothing but Hot Air', 3, 'Obtido após adquirir a montaria Haze (basta dar use em um Spectral Scrap of Cloth)', NULL),
('Nothing can stop me', 1, 'Obtido cortando Jungle Grass 100x', NULL),
('Number of the Beast', 2, 'Tirar o número 6 por 3x vezes seguidas no dado', NULL),
('Of Wolves and Bears', 6, 'Pode ser obtido fazendo os dois addons do Druid Outfits', NULL),
('One Foot vs. Many', 1, 'Obtido após faz a task "Extermination" da Bigfoot''s Burden Quest', NULL),
('One Less', 2, 'Obtido após falar para Grizzly Adams que você derrotou o boss The Many', NULL),
('One Thousand and One', 6, 'Pode ser obtido fazendo os dois addons do Oriental Outfits', NULL),
('Oops', 2, 'Obtido usando uma gaiola até o pássaro infartar', NULL),
('Out in the Snowstorm', 4, 'Pode ser obtido fazendo os dois addons do Norseman Outfits', NULL),
('Out of the Stone Age', 3, 'Obtido ao domar um Undead Cavebear', NULL),
('Party Animal', 1, 'Obtido usando 200x um Party Trumpet ou Party Hat', NULL),
('Peazzekeeper', 6, 'Obtido após conseguir os dois addons do Wayfarer Outfits', NULL),
('Pecking Order', 1, 'Obtido ao domar um Terror Bird', NULL),
('Perfect Fool', 3, 'Obtido fazendo a What a Foolish Quest', NULL),
('Personal Nightmare', 3, 'Obtido ao domar um Shock Head', NULL),
('Petrologist', 2, 'Obtido usando 100 Shiny Stones', NULL),
('Piece of Cake', 1, 'Você pode obtê-lo fazendo um Decorated Cake e um Chocolate Cake', NULL),
('Pig-Headed', 2, 'Obtido ao domar um Boar', NULL),
('Pimple', 3, 'Obtido após fazer a tarefa "Pore Stuffing" 50 vezes na War Against The Hive Quest', NULL),
('Planter', 2, 'Obtido após fazer a tarefa "Pore Stuffing" 10 vezes na War Against The Hive Quest', NULL),
('Polisher', 4, 'Obtido após você polir com sucesso 1 000 Rusty Armors ou Rusty Legs', NULL),
('Potion Addict', 4, 'Pode ser obtido bebendo 100.000 potions', NULL),
('Prison Break', 8, 'Obtido ao participar da luta contra o Gaz''Haragoth ou um de seus minions', NULL),
('Prospectre', 1, 'Obtido após derrotar o boss Thaian (Feaster of Souls Quest)', NULL),
('Pwned a Lot of Fur', 8, 'Obtido após matar todos os bosses da Paw and Fur Society disponíveis antes do Update 9.5', NULL);

INSERT INTO achievement (name, points, description, link) VALUES
('Pwned All Fur', 8, 'Obtido após matar todos os bosses da Paw and Fur Society', NULL),
('Quick as a Turtle', 2, 'Obtido após viajar pelo sea turtle em Laguna Islands 2.000 vezes', NULL),
('Raider in the Dark', 6, '[Exclusivo Taleon] Obtido após derrotar a The Queen Percht no evento de natal exclusivo do Taleon', NULL),
('Ransom Guy', 2, '[Exclusivo Taleon] Obtido ao terminar a Nomad''s Land Quest (após entregar a jewel case)', NULL),
('Rathleton Citizen', 1, 'Obtido ao ser promovido para o terceiro ranking de cidadão de Rathleton', NULL),
('Rathleton Commoner', 1, 'Obtido ao ser promovido para o primeiro ranking de cidadão de Rathleton', NULL),
('Rathleton Inhabitant', 1, 'Obtido ao ser promovido para o segundo ranking de cidadão de Rathleton', NULL),
('Rathleton Squire', 1, 'Obtido ao ser promovido para o quarto ranking de cidadão de Rathleton', NULL),
('Razing!', 7, 'Obtido após receber o rank de ''Razing'' na Vampire Hunter Quest (Entregando 100 Vampire Lord Tokens)', NULL),
('Recognised Trader', 3, 'Obtido após finalizar a The Travelling Trader Quest', NULL),
('Rhino Rider', 1, 'Obtido ao domar um Stone Rhino', NULL),
('Rift Warrior', 3, 'Pode ser obtido fazendo os dois addons do Rift Warrior Outfits', NULL),
('Ritualist', 6, 'Pode ser obtido fazendo os dois addons masculinos do Summoner Outfits ou os dois addons femininos do Mage Outfits', NULL),
('Rock Me to Sleep', 1, 'Obtido dormindo 100 vezes em uma rede (logout)', NULL),
('Rocket in Pocket', 1, 'Obtido usando 3 Fireworks Rockets em sua Backpack', NULL),
('Rockstar', 3, 'Obtido usando um instrumento musical 10.000 vezes', NULL),
('Rollercoaster', 1, 'Obtido viajando 100 vezes em um Ore Wagon', NULL),
('Rootless Behaviour', 1, 'Obtido após falar para Grizzly Adams que você derrotou o boss Deathbine', NULL),
('Running the Rift', 3, 'Obtido após adquirir a montaria Rift Runner, usando um Mysterious Scroll (drop de Ferumbras Mortal Shell)', NULL),
('Ruthless', 5, 'Obtido após finalizar a The Pits of Inferno Quest', NULL),
('Safely Stored Away', 2, 'Obtido ao pisar no depot por 1000 vezes', NULL),
('Santa''s Li''l Helper', 2, 'Obtido após abrir 25x Christmas Bundles (qualquer cor)', NULL),
('Scales and Tail', 2, 'Obtido ao domar um Draptor', NULL),
('Scorched Flames', 1, 'Obtido após falar para Grizzly Adams que você derrotou o boss Flameborn', NULL),
('Scourge of Scarabs', 3, 'Obtido após abrir um dos baús de recompensa em uma das salas após derrotar o Ancient Spawn of Morgathla (Dangerous Depths Quest)', NULL);

INSERT INTO achievement (name, points, description, link) VALUES
('Scrapper', 3, 'Obtido após finalizar a Barbarian Arena Quest na dificuldade ''Scrapper''', NULL),
('Seasoned Adventurer', 1, 'Obtido após atingir o Level 50', NULL),
('Secret Agent', 1, 'Obtido após começar a Secret Service Quest', NULL),
('Serious Contender', 4, 'Ao desbloquear totalmente 100 criaturas do nível médio você ganha o achievement', NULL),
('Shaburak Nemesis', 1, 'Obtido após matar 100 Shaburak Prince', NULL),
('Sharpshooter', 3, 'Obtido bebendo 100 Bullseye Potions (Apenas paladinos podem fazer este achievement)', NULL),
('Shell Seeker', 3, 'Obtido após encontrar 100 Giant Shimmering Pearls em Large Seashells', NULL),
('Ship''s Kobold', 4, 'Obtido após viajar cerca de 1.250 vezes de barco', NULL),
('Si, Ariki!', 1, 'Obtido ao iniciar um diálogo com Yasir pela primeira vez', NULL),
('Silent Pet', 1, 'Obtido pegando um peixe dourado com um Empty Goldfish Bowl', NULL),
('Skilled Hunter', 5, 'Ao desbloquear totalmente 10 criaturas do nível difícil você ganha o achievement', NULL),
('Skin-Deep', 4, 'Obtido usando 500 vezes (com sucesso) a sua Obsidian Knife nos monstros possíveis', NULL),
('Skull and Bones', 6, 'Pode ser obtido fazendo os dois addons do Brotherhood of Bones Outfits (Se você escolheu seguir os Nightmare Knights você não poderá fazer esse achievement)', NULL),
('Slim Chance', 1, 'Obtido usando um Treasure Map 100 vezes. Obs: Não funciona com um Pirate Treasure Map', NULL),
('Slimer', 1, 'Obtido após usar um Slime Gobbler por 500x em Slime Fungus', NULL),
('Slugging Around', 2, 'Obtido após domar uma Slug', NULL),
('Snowbunny', 2, 'Obtido após andar 10.000 sqms na neve', NULL),
('Something Smells', 1, 'Obtido após falar para Grizzly Adams que você derrotou o boss Sulphur Scuttler', NULL),
('Something''s in There', 1, 'Obtido ao pisar em uma Fallen Tree quando estiver aparecendo olhos nela', NULL),
('Spareribs for Dinner', 1, 'Obtido após falar para Grizzly Adams que você derrotou o boss Ribstride', NULL),
('Spin-Off', 1, 'Obtido ao domar uma Wailing Widow', NULL),
('Spolium Profundis', 4, 'Obtido após completar os dois addons do Deepling Outfits', NULL),
('Spore Hunter', 1, 'Obtido após fazer a task "Spores" da Bigfoot''s Burden Quest', NULL),
('Starless Night', 3, 'Obtido ao domar uma Midnight Panther', NULL),
('Steampunked', 2, 'Obtido após viajar 100 vezes com o steamboat', NULL);

INSERT INTO achievement (name, points, description, link) VALUES
('Stepped on a Big Toe', 1, 'Obtido após falar para Grizzly Adams que você derrotou o boss Tromphonyte', NULL),
('Stomach Ulcer', 4, 'Obtido após fazer a tarefa "Disrupt The Hives Digestion" 100 vezes na War Against The Hive Quest', NULL),
('Stuntman', 3, 'Obtido ao domar um Uniwheel', NULL),
('Substitute Tinker', 1, 'Obtido após completar pela primeira vez a task "The Tinker''s Bell" da Bigfoot''s Burden Quest', NULL),
('Superstitious', 2, 'Obtido após usar 100 Mysterious Voodoo Skull (a mensagem "It''s not the time yet" não conta)', NULL),
('Supplier', 3, 'Obtido após fazer a tarefa "Dissolved Chitin" 50 vezes na War Against The Hive Quest', NULL),
('Suppressor', 4, 'Obtido após fazer a tarefa "Pore Stuffing" 100 vezes na War Against The Hive Quest', NULL),
('Swamp Beast', 1, 'Obtido ao domar um Water Buffalo', NULL),
('Swashbuckler', 6, 'Pode ser obtido fazendo os dois addons do Pirate Outfits', NULL),
('Sweet Tooth', 2, 'Pode ser obtido fazendo 10 Chocolate Cakes', NULL),
('Swift Death', 6, 'Pode ser obtido fazendo os dois addons do Assassin Outfits', NULL),
('Talented Dancer', 1, 'Obtido após completar a missão 3 da Unnatural Selection Quest', NULL),
('Thais Savior', 5, '[Exclusivo Taleon] Obtido após ajudar a cidade de Thais doando sua mana aos NPCs na invasão do Ferumbras Revenge', NULL),
('The Cake''s the Truth', 1, 'Pode ser obtido fazendo 30 Cakes', NULL),
('The Drowned Sea God', 2, 'Obtido após falar para Grizzly Adams que você derrotou o boss Leviathan', NULL),
('The Gates of Hell', 2, 'Obtido após falar para Grizzly Adams que você derrotou o boss Kerberos', NULL),
('The Picky Pig', 1, 'Obtido após fazer a task "Mushroom Digging" da Bigfoot''s Burden Quest', NULL),
('The Professors Nut', 3, 'Obtido ao abrir o baú depois de derrotar o boss Professor Maxxen, concluindo a Hero of Rathleton Quest', NULL),
('The Right Tone', 1, 'Obtido ao domar um Crystal Wolf', NULL),
('The Serpent''s Bride', 2, 'Obtido após falar para Grizzly Adams que você derrotou o boss Gorgo', NULL),
('The Undertaker', 2, 'Obtido após abrir 500 buracos', NULL),
('Thick-Skinned', 2, 'Obtido ao domar um Stampor', NULL),
('Top AVIN Agent', 4, 'Obtido após terminar a Secret Service Quest seguindo a fação AVIN', NULL),
('Top CGB Agent', 4, 'Obtido após terminar a Secret Service Quest seguindo a fação CGB', NULL),
('Top TBI Agent', 4, 'Obtido após terminar a Secret Service Quest seguindo a fação TBI', NULL);

INSERT INTO achievement (name, points, description, link) VALUES
('True Dedication', 5, 'Pode ser obtido fazendo os dois addons do Demon Outfits', NULL),
('True Lightbearer', 5, 'Obtido após acender os dez Lightbearer Basins no evento The Lightbearer (apenas após o servidor completar com sucesso)', NULL),
('Turncoat', 4, 'Obtido após completar a In Service of Yalahar Quest quando você segue as instruções do Yalahari e do Palimuth', NULL),
('Twisted Mutation', 1, 'Obtido após falar para Grizzly Adams que você derrotou o boss Esmeralda', NULL),
('Umbral Archer', 6, 'Obtido ao criar um Umbral Master Bow', NULL),
('Umbral Berserker', 6, 'Obtido ao criar um Umbral Master Hammer', NULL),
('Umbral Bladelord', 6, 'Obtido ao criar uma Umbral Masterblade', NULL),
('Umbral Brawler', 6, 'Obtido ao criar um Umbral Master Mace', NULL),
('Umbral Executioner', 6, 'Obtido ao criar um Umbral Master Chopper', NULL),
('Umbral Harbinger', 3, 'Obtido após domar um Mole usando um Candle Stump', NULL),
('Umbral Harbinger', 6, 'Obtido ao criar um Umbral Master Spellbook', NULL),
('Umbral Headsman', 6, 'Obtido ao criar uma Umbral Master Axe', NULL),
('Umbral Marksman', 6, 'Obtido ao criar uma Umbral Master Crossbow', NULL),
('Umbral Master', 8, 'Obtido ao elevar todos os itens "Umbral" para "Umbral Master"', NULL),
('Umbral Swordsman', 6, 'Obtido ao criar uma Umbral Masterblade', NULL),
('Unleash the Beast', 8, 'Obtido após adquirir os 2 addons do Revenant Outfit (Outfit da Soul War)', NULL),
('Vanity', 3, 'Obtido ao usar um wall mirror (qualquer um deles) 300x estando bêbado. Necessário casa', NULL),
('Vortex Tamer', 5, 'Obtido após adquirir as montarias Neon Sparkid, Vortexion e Sparkion', NULL),
('Warlock', 6, 'Pode ser obtido fazendo os dois addons do Wizard Outfits', NULL),
('Warlord of Svargrond', 5, 'Obtido após finalizar a Barbarian Arena Quest na dificuldade ''Warlord''', NULL),
('Waverider', 2, 'Obtido ao nadar 100.000 sqms na praia (Em torno de 9 horas)', NULL),
('Way of The Shaman', 6, 'Pode ser obtido fazendo os dois addons do Shaman Outfits', NULL),
('Way to Hell', 2, 'Obtido ao domar um Magma Crawler', NULL),
('Wayfarer', 3, 'Obtido fazendo a missão 9 da Wrath of the Emperor Quest', NULL),
('Well Roared, Lion!', 1, 'Obtido após domar a criatura White Lion usando uma Red Silk Flower (Loot dos bosses do Lion Sanctum)', NULL),
('Wild Warrior', 6, 'Pode ser obtido fazendo os dois addons do Warrior Outfits', NULL),
('With a Cherry on Top', 1, 'Pode ser obtido decorando 20 Cakes com frutas', NULL),
('You got Horse Power', 8, 'Obtido após adquirir a montaria Phantasmal Jade (4 Spectral Horseshoes, 1 Spectral Horse Tack, 1 Spectral Saddle)', NULL),
('Zzztill Zzztanding!', 1, 'Obtido após falar para Grizzly Adams que você derrotou o boss Fazzrah', NULL),
('Up the Molehill', 3, 'Obtido ao domar um Mole', NULL);
